#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

       alias __INSTALL_DIR__/;
       index index.php;
       location ~ [^/]\.php(/|$) {
           fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
           include fastcgi_params_no_auth;
	   fastcgi_intercept_errors on;
       }
}
