#!/bin/bash
# In simple cases, you don't need a config script.

# With a simple config_panel.toml, you can write in the app settings, in the
# upstream config file or replace complete files (logo ...) and restart services.

# The config scripts allows you to go further, to handle specific cases
# (validation of several interdependent fields, specific getter/setter for a value,
# display dynamic informations or choices, pre-loading of config type .cube... ).

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

data_dir=$(ynh_app_setting_get --key=data_dir)
config_file="$data_dir/data/config.php"

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__server_long_desc() {
    value="$(grep "const SERVER_LONG_DESCRIPTION" "$config_file" | cut -d= -f 2 | sed 's/^\s*//;s/[ ;]*$//g')"
    if [ "$value" == "null" ]; then
        echo ""
    else
        echo "$value"
    fi
}

get__instances() {
    # Display one instance URL per line in the config panel's text area
    local urls="$(sed -n '/const INSTANCES = \[/,/\];/p' "$config_file" | sed '1d;$d' | sed 's/^[ \t"]*//' | sed 's/[ \t",]*$/,/')" #1. Extract, 2. Remove first and last lines, 3. Remove spaces, quotes and commas.
    echo -e "${urls//,/\\n}" #double newline required for proper display in config panel's text input box
}
#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__server_long_desc() {
    local content="$server_long_desc"
    if [ -z "$content" ]; then
        content="null"
    else
        content="\"$content\""
    fi
    ynh_replace --match="^\(\s*const SERVER_LONG_DESCRIPTION = \).*;$" --replace="\1$content;"  --file="$config_file"
}

set__instances() {
    inst_list=($(echo -e "$instances" | sed 's/\n/ /g'))
    # Generate the new array block
    array_block="\tconst INSTANCES = [\n"
    for url in "${inst_list[@]}"; do
      array_block+="\t\t\"$url\",\n"
    done
    array_block+="\t];"

    sed -i "/^\s*const INSTANCES = \[.*$/,/^\s*\];$/c\\$array_block" "$config_file"
    #ynh_store_file_checksum "$config_file"
}

#=================================================
ynh_app_config_run "$1"
